services:
    caddy:
        image: caddy:alpine
        container_name: php-app-caddy
        restart: unless-stopped
        working_dir: /var/www/html
        networks:
            main:
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./docker/dev/caddy/Caddyfile:/etc/caddy/Caddyfile
            - .:/var/www/html
        labels:
            caddy: "php-app.local"
            caddy.reverse_proxy: "{{upstreams http}}"

    php:
        build:
            context: .
            dockerfile: ./docker/dev/php/Dockerfile
            args:
                TZ: ${TZ:-Europe/Warsaw}
        container_name: php-app-php
        restart: unless-stopped
        working_dir: /var/www/html
        networks:
            main:
        volumes:
            - .:/var/www/html

networks:
    main:
        external: true

volumes:
    caddy_data:
    caddy_config:
